### PR TITLE
Forklift-a-tize

### PR DESCRIPTION
**Pull request by stdavis**
This is all set up and running on the server. However, it's erroring out when it tries to clean up the scratch data at the end. I'll let it run tomorrow morning at 10 and then you can see the error message in the report email.

### CODE REVIEW

**Comment by jacobdadams** [comment]
Thanks for the separate commits- they really make following the process easy. 

Just to verify, the basic process was:
* Wrap the functional code in the process() method of a forklift Pallet class.
* Log data using the logger provided by Pallet instead of printing.
* Various file name dressings.

Do I have that right?

**Comment by jacobdadams** [comment]
Could you please modify .gitignore with the newly renamed secrets file? 

I realize you probably don't push from the server's repo as a matter of principle, but I'm paranoid and like to have that hard check in place just in case (like if I'm doing a future change and accidentally `git add .`).

**Comment by jacobdadams** [comment]
Wait, I'm blind. Disregard the gitignore comment.

**Comment by stdavis** [comment]
> Do I have that right?

Yes. Other than renaming the secrets file to prevent collisions with other secrets in forklift.

**Pull request merged**
